gen_data['personatge'] = [
  'El teu port és <span id=fisic>{fisic}</span>, de pell <span id=pell>{pell}</span>, cabells <span id=cabells>{cabells}</span> i rostre <span id=rostre>{rostre}</span>. Parles amb una veu <span id=veu>{veu}</span> i duus roba <span id=vestimenta>{vestimenta}</span>. D\'esperit <span id=virtut>{virtut}</span> però alhora <span id=defecte>{defecte}</span>, i generalment se\'t considera <span id=reputacio>{reputacio}</span>. Tens l\'infortuni d\'haver sigut <span id=desgracia>{desgracia}</span>.'
]

gen_data['nom_addicional'] = [
 'Al·lòdia'
, 'Àtila'
, 'Bruniquilda'
, 'Calixta'
, 'Cira'
, 'Ermessenda'
, 'Eudòxia'
, 'Fulgència'
, 'Gaia'
, 'Gumersinda'
, 'Henedina'
, 'Hipòlita'
, 'Janina'
, 'Maximina'
, 'Nela'
, 'Rosamunda'
, 'Sança'
, 'Siara'
, 'Tàrsila'
, 'Zenòbia'
, 'Artemi'
, 'Brici'
, 'Cenobi'
, 'Clodovalt'
, 'Ermengot'
, 'Eutimi'
, 'Jucunt'
, 'Laerci'
, 'Lotari'
, 'Otger'
, 'Policroni'
, 'Pràxedis'
, 'Quiríac'
, 'Règul'
, 'Rossent'
, 'Sabaci'
, 'Saturi'
, 'Uiso'
, 'Ursí'
, 'Vit'
]

gen_data['cognom_addicional'] = [
 'Adel'
, 'Arn'
, 'Baixenc'
, 'Batllor'
, 'Castell'
, 'Comorer'
, 'Florens'
, 'Gaixe'
, 'Gonfau'
, 'Llambric'
, 'Lleonar'
, 'Matabos'
, 'Montany'
, 'Ordei'
, 'Pucurell'
, 'Puigdoller'
, 'Rovir'
, 'Surrallè'
, 'Ventur'
, 'Vilardel'
]

gen_data['nom'] = [
'Agune'
, 'Beatrice'
, 'Breagan'
, 'Bronwyn'
, 'Cannora'
, 'Drelil'
, 'Elgile'
, 'Esme'
, 'Griya'
, 'Henaine'
, 'Lirann'
, 'Lirathil'
, 'Lisabeth'
, 'Moralil'
, 'Morgwen'
, 'Sybil'
, 'Theune'
, 'Wenain'
, 'Ygwal'
, 'Yslen'
, 'Arwel'
, 'Bevan'
, 'Boroth'
, 'Borrid'
, 'Breagle'
, 'Breglor'
, 'Canhoreal'
, 'Emrys'
, 'Ethex'
, 'Gringle'
, 'Grinwit'
, 'Gruwid'
, 'Gruwth'
, 'Gwestin'
, 'Mannog'
, 'Melnax'
, 'Orthax'
, 'Triunein'
, 'Wenlan'
, 'Yirmeor'
]

gen_data['cognom'] = [
'Abernathy'
, 'Addercap'
, 'Burl'
, 'Candlewick'
, 'Cormick'
, 'Crumwaller'
, 'Dunswallow'
, 'Getri'
, 'Glass'
, 'Harkness'
, 'Harper'
, 'Loomer'
, 'Malksmilk'
, 'Smythe'
, 'Sunderman'
, 'Swinney'
, 'Thatcher'
, 'Tolmen'
, 'Weaver'
, 'Wolder'
]

gen_data['rerefons'] = [
   'Alquimista'
,  'Artista'
,  'Carnisser'
,  'Carterista'
,  'Caçador'
,  'Clergue'
,  'Comerciant'
,  'Contrabandista'
,  'Criminal'
,  'Enterrador'
,  'Explorador'
,  'Ferrer'
,  'Fuster'
,  'Herborista'
,  'Jugador'
,  'Lladre'
,  'Mag'
,  'Mercenari'
,  'Miner'
,  'Servent'
]

gen_data['rerefons_addicional'] = [
 'Aiguader'
, 'Barber'
, 'Bugadera'
, 'Carboner'
, 'Carreter'
, 'Cisteller'
, 'Dida'
, 'Emblanquinador'
, 'Esmolet'
, 'Espardenyer'
, 'Llauner'
, 'Marxant'
, 'Pastor'
, 'Puntaire'
, 'Retratista ambulant'
, 'Sabater'
, 'Sargidor'
, 'Titellaire'
, 'Trementinaire'
, 'Vidrier'
]

gen_data['fisic'] = [
  'atlètic'
,  'baix'
,  'cepat'
,  'escanyolit'
,  'escultural'
,  'gegantí'
,  'gros'
,  'llarguerut'
,  'musculós'
,  'robust'
]

gen_data['pell'] = [
  'bronzejada'
,  'endurida'
,  'fofa'
,  'fosca'
,  'llisa'
,  'amb marca de naixement'
,  'amb marques de verola'
,  'rosàcia'
,  'suau'
,  'tatuada'
]

gen_data['cabells'] = [
  'abundants'
,  'arrissats'
,  'bruts'
,  'inexistents (calb)'
,  'encrespats'
,  'escassos'
,  'greixosos'
,  'llargs'
,  'ondulats'
,  'trenats'
]

gen_data['rostre'] = [
  'allargat'
,  'demacrat'
,  'de rata'
,  'desﬁgurat'
,  'escultural'
,  'esmolat'
,  'pàl·lid'
,  'perfecte'
,  'quadrat'
,  'xuclat'
]

gen_data['veu'] = [
  'clara'
,  'directa'
,  'enigmàtica'
,  'estrident'
,  'formal'
,  'monòtona'
,  'profunda'
,  'ressonant'
,  'tartamuda'
,  'xiuxiuejant'
]

gen_data['vestimenta'] = [
  'antiga'
,  'bruta'
,  'elegant'
,  'enfangada'
,  'ensangonada'
,  'esparracada'
,  'exòtica'
,  'malgirbada'
,  'pestilent'
,  'd\'uniforme'
]

gen_data['virtut'] = [
  'ambiciós'
,  'disciplinat'
,  'honorable'
,  'humil'
,  'misericordiós'
,  'prudent'
,  'serè'
,  'sociable'
,  'tolerant'
,  'valent'
]

gen_data['defecte'] = [
  'agressiu'
,  'amargat'
,  'cobdiciós'
,  'covard'
,  'groller'
,  'mandrós'
,  'mentider'
,  'nerviós'
,  'vanitós'
,  'venjatiu'
]

gen_data['reputacio'] = [
  'ambiciós'
,  'divertit'
,  'excèntric'
,  'gandul'
,  'honest'
,  'pallús'
,  'perillós'
,  'repulsiu'
,  'respectat'
,  'savi'
]

gen_data['desgracia'] = [
  'abandonat'
,  'addicte'
,  'condemnat'
,  'degradat'
,  'desacreditat'
,  'desheretat'
,  'estafat'
,  'exiliat'
,  'maleït'
,  'víctima de xantatge'
]
/*
gen_data['equipament'] = [
  'armadura: {armadura}<br>Casc/Escut: {casc}<br>Armes: {armes}<br>Items: {eina,material,fotil}<br>Bonus item: {addicional}'
]*/
gen_data['armadura'] = {
  '1-3': 'sense armadura',
  '4-14': 'brigantina (1 armadura, voluminós)',
  '15-19': 'cota de malles (2 armadura, voluminós)',
  '20': 'armadura completa (3 armadura, voluminós)'
}

gen_data['casc'] = {
  '1-13': ', sense casc ni escut',
  '14-16': ', un casc (+1 Armadura)',
  '17-19': ', un escut (+1 Armadura)',
  '20': ', un casc i un escut (+2 Armadura)'
}

gen_data['armes'] = {
'1-10':'{gruparmes1}',
'11-14':'{gruparmes2}',
'15-19':'{gruparmes3}',
'20':'{gruparmes4}'
}

gen_data['gruparmes1'] = ['daga', 'garrot', 'bàcul']
gen_data['gruparmes2'] = ['espasa', 'maça', 'destral']
gen_data['gruparmes3'] = ['arc (voluminós)', 'ballesta (voluminós)', 'fona']
gen_data['gruparmes4'] = ['alabarda (voluminós)', 'martell de guerra (voluminós)', 'destral de guerra (voluminós)']

gen_data['armadura_armes'] = {
  '1-10':'{armadura}',
  '11-20':'{armes}'
}

gen_data['eina_fotil'] = {
  '1-10':'{eina}',
  '11-20':'{fotil}'
}

gen_data['addicional'] = {
  '1-6': '{eina_fotil}',
  '7-13': '{material}',
  '14-17': '{armadura_armes}',
  '18-20': 'llibre amb l\'encanteri \'{llibredencanteris}\''
}

gen_data['eina'] = [
  'canya de pescar'
,  'cisell'
,  'claus (apilable)'
,  'cola (apilable)'
,  'galleda (apilable)'
,  'greix'
,  'guix'
,  'llima de metall (apilable)'
,  'manxa'
,  'martell'
,  'obriülls'
,  'olla per cuinar'
,  'pala'
,  'palanca'
,  'pinces'
,  'rellotge de sorra'
,  'segellador'
,  'serra'
,  'trepant manual'
,  'xarxa (apilable)'
]

gen_data['fotil'] = [
  'ampolla'
,  'bales de vidre (apilable)'
,  'campaneta'
,  'cordill (apilable)'
,  'corn'
,  'encens (apilable)'
,  'esponja'
,  'instrument musical'
,  'joc de cartes (apilable)'
,  'joc de daus (apilable)'
,  'joies falses (apilable)'
,  'lupa'
,  'maquillatge'
,  'mirall'
,  'paquet de sal (apilable)'
,  'perfum'
,  'ploma i tinta'
,  'pot de brea'
,  'sabó (apilable)'
,  'xiulet'
]

gen_data['material'] = [
  'amulet contra els esperits'
,  'antitoxina'
,  'baló per bussejar'
,  'cadena (10 peus)'
,  'caixa d\'esca'
,  'carretó (+4 espais, voluminós)'
,  'corda (25 peus)'
,  'ganxo d\'escalada'
,  'manilles'
,  'oli per cremar'
,  'pal (10 peus)'
,  'pic'
,  'planta d\'acònit'
,  'politja'
,  'repel·lent'
,  'rossinyols'
,  'sac gran'
,  'trampa gran'
,  'ullera de llarga vista'
,  'vareta de saurí'
]

gen_data['llibredencanteris'] = [
'Accelerar (1)'
,  'Adherir (2)'
,  'Adormir (3)'
,  'Aire líquid (4)'
,  'Alçar els morts (5)'
,  'Àncora (6)'
,  'Antropomorﬁtzar (7)'
,  'Atenuar màgia (8)'
,  'Atraure (9)'
,  'Bales de vidre (10)'
,  'Bengala (11)'
,  'Brollar (12)'
,  'Canvi gravitacional (13)'
,  'Canviar de lloc (14)'
,  'Cobdícia (15)'
,  'Comandar (16)'
,  'Comprendre (17)'
,  'Con d‘escuma (18)'
,  'Controlar el clima (19)'
,  'Controlar el temps (20)'
,  'Controlar plantes (21)'
,  'Convertir en objectiu (22)'
,  'Convocar cub (23)'
,  'Convocar ídol (24)'
,  'Desmuntar (25)'
,  'Desplaçar (26)'
,  'Detectar màgia (27)'
,  'Disfressar (28)'
,  'Eixam (29)'
,  'Elasticitat (30)'
,  'Empènyer/estirar (31)'
,  'Encisar (32)'
,  'Ensordir (33)'
,  'Ensumar (34)'
,  'Pas entre miralls (35)'
,  'Escalar com una aranya (36)'
,  'Escoltar xiuxiueigs (37)'
,  'Esculpir elements (38)'
,  'Escut (39)'
,  'Esfera nocturna (40)'
,  'Espectacle (41)'
,  'Espiar (42)'
,  'Evolució primigènia (43)'
,  'Flor d\'esquer (44)'
,  'Flotar (45)'
,  'Fòbia (46)'
,  'Forma de bèstia (47)'
,  'Forma de fum (48)'
,  'Forma gelatinosa (49)'
,  'Fossa (50)'
,  'Frenesí (51)'
,  'Giny (52)'
,  'Guarir ferides (53)'
,  'Hipnotitzar (54)'
,  'Identiﬁcar el propietari (55)'
,  'Il·luminar (56)'
,  'Il·lusió auditiva (57)'
,  'Il·lusió visual (58)'
,  'Imatge reﬂectida (59)'
,  'Intercanvi de cossos (60)'
,  'Invocar esperit (61)'
,  'Llegir la ment (62)'
,  'Lligam invisible (63)'
,  'Marca de mag (64)'
,  'Màscara (65)'
,  'Matollar (66)'
,  'Matxet (67)'
,  'Minvar (68)'
,  'Mur elemental (69)'
,  'Núvol de boira (70)'
,  'Objecte animat (71)'
,  'Obrir (72)'
,  'Odi (73)'
,  'Ofuscar (74)'
,  'Ordenar (75)'
,  'Paciﬁcar (76)'
,  'Pispar (77)'
,  'Portal (78)'
,  'Presó astral (79)'
,  'Protegir (80)'
,  'Refugi (81)'
,  'Relliscar (82)'
,  'Repel·lir (83)'
,  'Saltar (84)'
,  'Sentir (85)'
,  'Sufocar (86)'
,  'Telecinesi (87)'
,  'Telepatia (88)'
,  'Teletransportar (89)'
,  'Teranyina (90)'
,  'Terratrèmol (91)'
,  'Toc glaçat (92)'
,  'Transformar en objecte (93)'
,  'Tres braços (94)'
,  'Ull arcà (95)'
,  'Vel (96)'
,  'Ventrilòquia (97)'
,  'Visió (98)'
,  'Visió de raigs X (99)'
,  'Visió veritable (100)'
]
